package com.gh.wedding.dto

data class InvitationSaveRequest(
    val slug: String? = null,
    val groomName: String? = null,
    val brideName: String? = null,
    val date: String? = null,
    val locationName: String? = null,
    val address: String? = null,
    val message: String? = null,
    val mainImageUrl: String? = null,
    val imageUrls: List<String>? = null,
    val paperInvitationUrl: String? = null,
    val groomContact: String? = null,
    val brideContact: String? = null,
    val accountNumber: String? = null,
    val useSeparateAccounts: Boolean? = null,
    val groomAccountNumber: String? = null,
    val brideAccountNumber: String? = null,
    val groomRelation: String? = null,
    val groomFatherName: String? = null,
    val groomFatherContact: String? = null,
    val groomMotherName: String? = null,
    val groomMotherContact: String? = null,
    val brideRelation: String? = null,
    val brideFatherName: String? = null,
    val brideFatherContact: String? = null,
    val brideMotherName: String? = null,
    val brideMotherContact: String? = null,
    val bus: String? = null,
    val subway: String? = null,
    val car: String? = null,
    val fontFamily: String? = null,
    val fontColor: String? = null,
    val fontSize: Int? = null,
    val heroMainFontFamily: String? = null,
    val heroMainFontColor: String? = null,
    val heroMainFontSize: Int? = null,
    val heroSubFontFamily: String? = null,
    val heroSubFontColor: String? = null,
    val heroSubFontSize: Int? = null,
    val useGuestbook: Boolean? = null,
    val useRsvpModal: Boolean? = null,
    val rsvpAutoOpenOnLoad: Boolean? = null,
    val backgroundMusicUrl: String? = null,
    val seoTitle: String? = null,
    val seoDescription: String? = null,
    val seoImageUrl: String? = null,
    val galleryTitle: String? = null,
    val galleryType: String? = null,
    val themeBackgroundColor: String? = null,
    val themeTextColor: String? = null,
    val themeAccentColor: String? = null,
    val themePatternColor: String? = null,
    val themePattern: String? = null,
    val themeEffectType: String? = null,
    val themeFontFamily: String? = null,
    val themeFontSize: Int? = null,
    val themeScrollReveal: Boolean? = null,
    // 추가된 필드들
    val heroDesignId: String? = null,
    val heroEffectType: String? = null,
    val heroEffectParticleCount: Int? = null,
    val heroEffectSpeed: Int? = null,
    val heroEffectOpacity: Int? = null,
    val heroAccentFontFamily: String? = null,
    val messageFontFamily: String? = null,
    val transportFontFamily: String? = null,
    val rsvpTitle: String? = null,
    val rsvpMessage: String? = null,
    val rsvpButtonText: String? = null,
    val rsvpFontFamily: String? = null,
    val detailContent: String? = null,
    val detailFontFamily: String? = null,
    val locationTitle: String? = null,
    val locationFloorHall: String? = null,
    val locationContact: String? = null,
    val showMap: Boolean? = null,
    val lockMap: Boolean? = null,
    val openingEnabled: Boolean? = null,
    val openingAnimationType: String? = null,
    val openingBackgroundType: String? = null,
    val openingBackgroundColor: String? = null,
    val openingImageUrl: String? = null,
    val openingTitle: String? = null,
    val openingMessage: String? = null,
    val openingFontFamily: String? = null,
    val openingFontColor: String? = null,
    val openingTitleFontSize: Int? = null,
    val openingMessageFontSize: Int? = null,
)

data class InvitationPublishRequest(
    val slug: String? = null,
)

data class SlugCheckResponse(
    val slug: String,
    val available: Boolean,
)

data class InvitationPublishResponse(
    val invitationId: Long,
    val slug: String,
    val shareUrl: String,
)

data class InvitationEditorResponse(
    val id: Long,
    val slug: String?,
    val published: Boolean,
    val updatedAt: String?,
    val groomName: String?,
    val brideName: String?,
    val date: String?,
    val locationName: String?,
    val address: String?,
    val message: String?,
    val mainImageUrl: String?,
    val imageUrls: List<String>,
    val paperInvitationUrl: String?,
    val groomContact: String?,
    val brideContact: String?,
    val accountNumber: String?,
    val useSeparateAccounts: Boolean,
    val groomAccountNumber: String?,
    val brideAccountNumber: String?,
    val groomRelation: String?,
    val groomFatherName: String?,
    val groomFatherContact: String?,
    val groomMotherName: String?,
    val groomMotherContact: String?,
    val brideRelation: String?,
    val brideFatherName: String?,
    val brideFatherContact: String?,
    val brideMotherName: String?,
    val brideMotherContact: String?,
    val bus: String?,
    val subway: String?,
    val car: String?,
    val fontFamily: String?,
    val fontColor: String?,
    val fontSize: Int?,
    val heroMainFontFamily: String?,
    val heroMainFontColor: String?,
    val heroMainFontSize: Int?,
    val heroSubFontFamily: String?,
    val heroSubFontColor: String?,
    val heroSubFontSize: Int?,
    val useGuestbook: Boolean,
    val useRsvpModal: Boolean,
    val rsvpAutoOpenOnLoad: Boolean,
    val backgroundMusicUrl: String?,
    val seoTitle: String?,
    val seoDescription: String?,
    val seoImageUrl: String?,
    val galleryTitle: String?,
    val galleryType: String?,
    val themeBackgroundColor: String?,
    val themeTextColor: String?,
    val themeAccentColor: String?,
    val themePatternColor: String?,
    val themePattern: String?,
    val themeEffectType: String?,
    val themeFontFamily: String?,
    val themeFontSize: Int?,
    val themeScrollReveal: Boolean,
    // 추가된 필드들
    val heroDesignId: String?,
    val heroEffectType: String?,
    val heroEffectParticleCount: Int?,
    val heroEffectSpeed: Int?,
    val heroEffectOpacity: Int?,
    val heroAccentFontFamily: String?,
    val messageFontFamily: String?,
    val transportFontFamily: String?,
    val rsvpTitle: String?,
    val rsvpMessage: String?,
    val rsvpButtonText: String?,
    val rsvpFontFamily: String?,
    val detailContent: String?,
    val detailFontFamily: String?,
    val locationTitle: String?,
    val locationFloorHall: String?,
    val locationContact: String?,
    val showMap: Boolean,
    val lockMap: Boolean,
    val openingEnabled: Boolean,
    val openingAnimationType: String?,
    val openingBackgroundType: String?,
    val openingBackgroundColor: String?,
    val openingImageUrl: String?,
    val openingTitle: String?,
    val openingMessage: String?,
    val openingFontFamily: String?,
    val openingFontColor: String?,
    val openingTitleFontSize: Int?,
    val openingMessageFontSize: Int?,
)

data class MyInvitationResponse(
    val id: Long,
    val slug: String?,
    val published: Boolean,
    val title: String,
    val weddingDate: String?,
    val mainImageUrl: String?,
    val updatedAt: String?,
)

data class PublicInvitationResponse(
    val id: String,
    val slug: String,
    val groomName: String,
    val brideName: String,
    val weddingDateTime: String,
    val venueName: String,
    val venueAddress: String,
    val coverImageUrl: String,
    val mainImageUrl: String?,
    val mapImageUrl: String,
    val imageUrls: List<String>,
    val messageLines: List<String>,
    val seoTitle: String?,
    val seoDescription: String?,
    val seoImageUrl: String?,
    val galleryTitle: String?,
    val galleryType: String?,
    val themeBackgroundColor: String?,
    val themeTextColor: String?,
    val themeAccentColor: String?,
    val themePatternColor: String?,
    val themePattern: String?,
    val themeEffectType: String?,
    val themeFontFamily: String?,
    val themeFontSize: Int?,
    val themeScrollReveal: Boolean,
    // 추가 필드
    val heroDesignId: String?,
    val heroEffectType: String?,
    val heroEffectParticleCount: Int?,
    val heroEffectSpeed: Int?,
    val heroEffectOpacity: Int?,
    val heroAccentFontFamily: String?,
    val message: String?,
    val messageFontFamily: String?,
    val transportFontFamily: String?,
    val rsvpTitle: String?,
    val rsvpMessage: String?,
    val rsvpButtonText: String?,
    val rsvpFontFamily: String?,
    val detailContent: String?,
    val detailFontFamily: String?,
    val locationTitle: String?,
    val locationFloorHall: String?,
    val locationContact: String?,
    val showMap: Boolean,
    val lockMap: Boolean,
    val openingEnabled: Boolean,
    val openingAnimationType: String?,
    val openingBackgroundType: String?,
    val openingBackgroundColor: String?,
    val openingImageUrl: String?,
    val openingTitle: String?,
    val openingMessage: String?,
    val openingFontFamily: String?,
    val openingFontColor: String?,
    val openingTitleFontSize: Int?,
    val openingMessageFontSize: Int?,
    val subway: String?,
    val bus: String?,
    val car: String?,
    val useGuestbook: Boolean,
    val useRsvpModal: Boolean,
    val rsvpAutoOpenOnLoad: Boolean,
    val backgroundMusicUrl: String?,
    val fontFamily: String?,
    val fontColor: String?,
    val fontSize: Int?,
    val heroMainFontFamily: String?,
    val heroMainFontColor: String?,
    val heroMainFontSize: Int?,
    val heroSubFontFamily: String?,
    val heroSubFontColor: String?,
    val heroSubFontSize: Int?,
    val accountNumber: String?,
    val useSeparateAccounts: Boolean,
    val groomAccountNumber: String?,
    val brideAccountNumber: String?,
    val groomContact: String?,
    val brideContact: String?,
    val groomFatherName: String?,
    val groomFatherContact: String?,
    val groomMotherName: String?,
    val groomMotherContact: String?,
    val brideFatherName: String?,
    val brideFatherContact: String?,
    val brideMotherName: String?,
    val brideMotherContact: String?,
)
